language: python
# command to install dependencies
install:
  - "pip install tox"
# run before the main script
before_script:
  - "git --version"
# command to run tests
script: tox
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=style
# The following line tells Travis CI to build in a container
sudo: false
